"""add refresh token

Revision ID: 1f2272f3ec06
Revises: 13b5a348c080
Create Date: 2022-02-14 16:38:37.455972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f2272f3ec06'
down_revision = '13b5a348c080'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_id', table_name='user')
    op.drop_table('user')
    op.drop_index('ix_book_id', table_name='book')
    op.drop_table('book')
    op.drop_index('ix_scrapbook_id', table_name='scrapbook')
    op.drop_table('scrapbook')
    op.drop_index('ix_scrap_id', table_name='scrap')
    op.drop_table('scrap')
    op.drop_table('scrapbook_users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrapbook_users',
    sa.Column('userId', sa.INTEGER(), nullable=True),
    sa.Column('scrapbookId', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['scrapbookId'], ['scrapbook.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ondelete='CASCADE')
    )
    op.create_table('scrap',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=True),
    sa.Column('page', sa.INTEGER(), nullable=False),
    sa.Column('picture', sa.VARCHAR(length=120), nullable=False),
    sa.Column('userId', sa.INTEGER(), nullable=False),
    sa.Column('scrapbookId', sa.INTEGER(), nullable=False),
    sa.Column('createdAt', sa.DATETIME(), nullable=False),
    sa.Column('updatedAt', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['scrapbookId'], ['scrapbook.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('picture')
    )
    op.create_index('ix_scrap_id', 'scrap', ['id'], unique=False)
    op.create_table('scrapbook',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('uuid', sa.VARCHAR(length=20), nullable=False),
    sa.Column('bookId', sa.INTEGER(), nullable=False),
    sa.Column('createdAt', sa.DATETIME(), nullable=False),
    sa.Column('updatedAt', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['bookId'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('ix_scrapbook_id', 'scrapbook', ['id'], unique=False)
    op.create_table('book',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('author', sa.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_book_id', 'book', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password', sa.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_id', 'user', ['id'], unique=False)
    # ### end Alembic commands ###
