"""cascade & is_starred

Revision ID: 375f0fe97028
Revises: f19da029a38c
Create Date: 2022-03-10 20:38:30.538725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '375f0fe97028'
down_revision = 'f19da029a38c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scrapbook_star', 'is_starred',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scrapbook_star', 'is_starred',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
