"""test8

Revision ID: 44808b579cf5
Revises: 89369f24aabe
Create Date: 2022-03-09 18:20:55.634532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44808b579cf5'
down_revision = '89369f24aabe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scrapbook', 'uuid',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=40),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scrapbook', 'uuid',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
