"""scrapbooks in book

Revision ID: 526f4b695e98
Revises: eeea8d8522f4
Create Date: 2022-03-09 17:47:48.841193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '526f4b695e98'
down_revision = 'eeea8d8522f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
