"""update default value

Revision ID: 59b9eda11e63
Revises: 238c4eda0fbc
Create Date: 2022-03-14 00:30:36.372126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59b9eda11e63'
down_revision = '238c4eda0fbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
