"""test2

Revision ID: 641776abc337
Revises: 1f35708bb13d
Create Date: 2022-02-14 17:51:59.228085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '641776abc337'
down_revision = '1f35708bb13d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
