"""test5

Revision ID: 6b7c03af8671
Revises: ac8e93856e0c
Create Date: 2022-03-09 18:11:55.188749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b7c03af8671'
down_revision = 'ac8e93856e0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
