"""test6

Revision ID: 759a62b141cd
Revises: 6b7c03af8671
Create Date: 2022-03-09 18:13:58.007027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '759a62b141cd'
down_revision = '6b7c03af8671'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
