"""test7

Revision ID: 89369f24aabe
Revises: 759a62b141cd
Create Date: 2022-03-09 18:15:58.018850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89369f24aabe'
down_revision = '759a62b141cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
