"""init

Revision ID: 91cfbf618b82
Revises: 1f2272f3ec06
Create Date: 2022-02-14 16:42:40.567462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91cfbf618b82'
down_revision = '1f2272f3ec06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
