"""test4

Revision ID: ac8e93856e0c
Revises: f73ef5d6a065
Create Date: 2022-03-09 18:08:53.631482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac8e93856e0c'
down_revision = 'f73ef5d6a065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
