"""scrapbook star backref

Revision ID: ce005f3540f9
Revises: 8af960e6c0c9
Create Date: 2022-03-14 00:44:58.493510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce005f3540f9'
down_revision = '8af960e6c0c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
