"""add url in book

Revision ID: cf7679866751
Revises: 9f5a6426e51e
Create Date: 2022-02-21 17:38:48.885192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf7679866751'
down_revision = '9f5a6426e51e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    op.rename_table('_book', 'book')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('book', '_book')
    op.create_table('book',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=120), nullable=False),
        sa.Column('authors', sa.String(length=120), nullable=False),
        sa.Column('publisher', sa.String(length=120), nullable=False),
        sa.Column('contents', sa.Text(), nullable=False),
        sa.Column('thumbnail', sa.String(length=180), nullable=False)
    )
    # ### end Alembic commands ###
