"""extend thumbnail, url

Revision ID: d81fe8749bde
Revises: ce005f3540f9
Create Date: 2022-03-15 22:46:43.600014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd81fe8749bde'
down_revision = 'ce005f3540f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'thumbnail',
               existing_type=sa.VARCHAR(length=180),
               type_=sa.String(length=1000),
               existing_nullable=False)
    op.alter_column('book', 'url',
               existing_type=sa.VARCHAR(length=180),
               type_=sa.String(length=1000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'url',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=180),
               existing_nullable=False)
    op.alter_column('book', 'thumbnail',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=180),
               existing_nullable=False)
    # ### end Alembic commands ###
