"""updatedAt default value

Revision ID: dea3f5527aec
Revises: 375f0fe97028
Create Date: 2022-03-14 00:10:40.492227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dea3f5527aec'
down_revision = '375f0fe97028'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
