"""test3

Revision ID: eb62961236de
Revises: 641776abc337
Create Date: 2022-02-14 17:55:22.746035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb62961236de'
down_revision = '641776abc337'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('author', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_id'), 'book', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('refreshToken', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('scrapbook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=20), nullable=False),
    sa.Column('bookId', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bookId'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_scrapbook_id'), 'scrapbook', ['id'], unique=False)
    op.create_table('scrap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('picture', sa.String(length=120), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('scrapbookId', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scrapbookId'], ['scrapbook.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('picture')
    )
    op.create_index(op.f('ix_scrap_id'), 'scrap', ['id'], unique=False)
    op.create_table('scrapbook_users',
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('scrapbookId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scrapbookId'], ['scrapbook.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scrapbook_users')
    op.drop_index(op.f('ix_scrap_id'), table_name='scrap')
    op.drop_table('scrap')
    op.drop_index(op.f('ix_scrapbook_id'), table_name='scrapbook')
    op.drop_table('scrapbook')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_book_id'), table_name='book')
    op.drop_table('book')
    # ### end Alembic commands ###
