"""uuid size up

Revision ID: f12d08ec50eb
Revises: 526f4b695e98
Create Date: 2022-03-09 18:00:18.048504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f12d08ec50eb'
down_revision = '526f4b695e98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
