"""cascade & is_starred

Revision ID: f19da029a38c
Revises: 44808b579cf5
Create Date: 2022-03-10 20:36:29.485832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f19da029a38c'
down_revision = '44808b579cf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scrapbook_star', sa.Column('is_starred', sa.Boolean()))
    op.drop_constraint('scrapbook_star_userId_fkey', 'scrapbook_star', type_='foreignkey')
    op.drop_constraint('scrapbook_star_scrapbookId_fkey', 'scrapbook_star', type_='foreignkey')
    op.create_foreign_key(None, 'scrapbook_star', 'user', ['userId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'scrapbook_star', 'scrapbook', ['scrapbookId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scrapbook_star', type_='foreignkey')
    op.drop_constraint(None, 'scrapbook_star', type_='foreignkey')
    op.create_foreign_key('scrapbook_star_scrapbookId_fkey', 'scrapbook_star', 'scrapbook', ['scrapbookId'], ['id'])
    op.create_foreign_key('scrapbook_star_userId_fkey', 'scrapbook_star', 'user', ['userId'], ['id'])
    op.drop_column('scrapbook_star', 'is_starred')
    # ### end Alembic commands ###
