"""test

Revision ID: f73ef5d6a065
Revises: f12d08ec50eb
Create Date: 2022-03-09 18:04:43.945133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f73ef5d6a065'
down_revision = 'f12d08ec50eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
