"""empty message

Revision ID: 361bca07cb79
Revises: 
Create Date: 2022-02-04 17:06:42.760070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '361bca07cb79'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bookname', sa.String(length=120), nullable=False),
    sa.Column('author', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('scrap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('picture', sa.String(length=120), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('bookId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bookId'], ['book.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('picture')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scrap')
    op.drop_table('user')
    op.drop_table('book')
    # ### end Alembic commands ###
